# LegendaryCraft V3 configuration

# Database configuration
# SQLite database file name stored in the plugin data folder
# If you change this, restart the server to recreate/connect to the new file.
database:
  file: storage.db

chest:
  max_per_team_member: 2